### ISSUE TITLE
And GetCursorPosition?

### ISSUE THREAD

**Issue by SrDobrais** [dotnet/dotnet-api-docs.es-es#11]
Buen día:
SetCursorPosition permite posicionar el cursor en consola, 
¿no existe el método GetCursorPosition que retorne el valor de dicha posición?
¡Gracias! 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 76a64a3a-03e2-b42d-5332-160721800340
* Version Independent ID: 28e035b9-4ce5-fc9f-82ff-24b93cf93a67
* Content: [Console.SetCursorPosition(Int32, Int32) Method (System)](https://docs.microsoft.com/es-es/dotnet/api/system.console.setcursorposition?view=netframework-4.7.2)
* Content Source: [xml/System/Console.xml](https://github.com/dotnet/dotnet-api-docs.es-es/blob/live/xml/System/Console.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hola, @SrDobrais 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by SrDobrais** [comment]
¡Gracias!
En [System_ConsoleKeyInfo_KeyChar](https://docs.microsoft.com/es-es/dotnet/api/system.consolekeyinfo.keychar?view=netframework-4.7.2#System_ConsoleKeyInfo_KeyChar)

```
`public class Example

{ 
    public static void Main()  

    {  

        // Configura la consola.  

        /*   

         * Las siguiente línes no compilan y mandan:

         *    Excepción no controlada: 

         *    System.ArgumentOutOfRangeException: 

         *    El tamaño de búfer de consola no debe ser menor que

         *    el tamaño actual ni que la posición de la ventana de consola, 

         *    ni mayor que o igual a Int16.MaxValue.

         *    Nombre del parámetro: width

         *    Valor actual 80.

         *    en System.Console.SetBufferSize(Int32 width, Int32 height)

         *    en System.Console.set_BufferWidth(Int32 value)

         *    en EjemploKeyChar.Main() en MiDirectorio\Archivo.cs:línea 28

         * 

         * ¡Creo que ya entendí!

         * El valor de Console.BufferWidth en la configuracion de la consola era de 120

         * por eso no me aceptaba el valor propuesto.

         * Cambie el valor en la configuración a 50 y ahora funciona bien.

         * 

         * El programa debería verificar el valor de de la pantalla antes de realizar el cambio.

        */
        Console.BufferWidth = 80;`
```

Por eso lo preguntaba.
