### ISSUE TITLE
RemoveNamespace 

### ISSUE THREAD

**Issue by jabmmx** [dotnet/dotnet-api-docs.es-es#12]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 4f5575e4-977b-6099-4119-b616c4bacbc4
* Version Independent ID: cf1987b6-01be-5933-b7cd-c66e896ae669
* Content: [XmlNamespaceManager.RemoveNamespace(String, String) Method (System.Xml)](https://docs.microsoft.com/es-es/dotnet/api/system.xml.xmlnamespacemanager.removenamespace?view=netframework-4.7.2)
* Content Source: [xml/System.Xml/XmlNamespaceManager.xml](https://github.com/dotnet/dotnet-api-docs.es-es/blob/live/xml/System.Xml/XmlNamespaceManager.xml)
* Product: **dotnet-api**
* Technology: **system.xml**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hola, @jabmmx 

Valoramos enormemente su comentario y estamos haciendo todo lo posible por mejorar su experiencia en docs.microsoft.com. No obstante, necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario?

Atentamente,
Equipo internacional de Microsoft DOCS

**Comment by CeciAc** [comment]
Hola, @jabmmx

Esta es una continuación de nuestro comentario anterior. Necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario?

Atentamente,
Equipo internacional de Microsoft DOCS

**Comment by CeciAc** [comment]
Hola, @jabmmx

Gracias nuevamente por su comentario.

Lamentablemente, aún nos falta información y no podemos procesar sus comentarios. En este momento, cerraremos este problema de GitHub, pero le animamos a enviar más comentarios en el futuro.

Atentamente,
Equipo internacional de Microsoft DOCS
