### ISSUE TITLE
Descripción incorrecta.

### ISSUE THREAD

**Issue by aralmo** [dotnet/dotnet-api-docs.es-es#13]
Proporciona la funcionalidad básica para servidores proxy. debería ser Proporciona la funcionalidad básica para clases proxy.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 1fc23492-1178-93de-01f0-356dd98d0023
* Version Independent ID: 3b91a964-8034-b138-8674-cfe7f70b67c9
* Content: [RealProxy Class (System.Runtime.Remoting.Proxies)](https://docs.microsoft.com/es-es/dotnet/api/system.runtime.remoting.proxies.realproxy?view=netframework-4.8#feedback)
* Content Source: [xml/System.Runtime.Remoting.Proxies/RealProxy.xml](https://github.com/dotnet/dotnet-api-docs.es-es/blob/live/xml/System.Runtime.Remoting.Proxies/RealProxy.xml)
* Product: **dotnet-api**
* Technology: **system.runtime**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hola, @<nombre de GITHUB del colaborador>: 


Gracias por sus comentarios lingüísticos.  

Después de revisarlos, el equipo lingüístico ha considerado que no cumplen con los criterios mínimos de aceptación porque [la traducción es precisa y se corresponde con el inglés]. 

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios.  

Atentamente, 

Equipo internacional de Microsoft Docs
