### ISSUE TITLE
Importar

### ISSUE THREAD

**Issue by lescudero74** [dotnet/dotnet-api-docs.es-es#3]
hola buenos días, quería saber como puedo incorporar estas clases a mi proyecto en c, no se si haya que descargarlas e incorporarlas en el directorio o como.
desde ya muchas gracias!
saludos!!

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: a881f299-0f0f-c4dc-7c92-6be0580f6f90
* Version Independent ID: 4aff9348-b89d-5197-8dde-966cc4c37840
* Content: [System.Web.Script.Serialization Namespace](https://docs.microsoft.com/es-es/dotnet/api/system.web.script.serialization?view=netframework-4.7.2#classes)
* Content Source: [xml/ns-System.Web.Script.Serialization.xml](https://github.com/dotnet/dotnet-api-docs.es-es/blob/live/xml/ns-System.Web.Script.Serialization.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hola, @lescudero74 :

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
