### ISSUE TITLE
importar libreria

### ISSUE THREAD

**Issue by lescudero74** [dotnet/dotnet-api-docs.es-es#4]
hola buenas tardes
quería saber como se puede incluir la libreria o lo que sea para poder utilizar la clase JavaScriptSerializer, estoy trabajando con un proyecto en c.
desde ya muchas gracias

**Comment by LisandroSu** [comment]
Hola, @lescudero74 :

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
