### ISSUE TITLE
Nombre del tipo o del espacio de nombres no encontrado

### ISSUE THREAD

**Issue by AlanUAZ** [dotnet/dotnet-api-docs.es-es#8]
Hola, no puedo usar esta clase a pesar de que ya importe la directiva using System.Web y la versión de Framework que uso es la 4.7.03056. ¿Cual podría ser el problema?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: f3d07391-b795-107c-390e-ced0753cac7c
* Version Independent ID: 00d7b107-ac15-fac0-a7b8-fc1f2639f8e7
* Content: [HttpPostedFileBase Class (System.Web)](https://docs.microsoft.com/es-mx/dotnet/api/system.web.httppostedfilebase?view=netframework-4.7)
* Content Source: [xml/System.Web/HttpPostedFileBase.xml](https://github.com/dotnet/dotnet-api-docs.es-es/blob/live/xml/System.Web/HttpPostedFileBase.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hola, @AlanUAZ 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
